### ISSUE TITLE
Building failed using makefile on Debian 10

### ISSUE THREAD

**Issue by xavier-niu** [apache/dubbo-go-samples#101]
`ifconfig` is removed from Debian 10, there is an error occurred when trying to retrieve `DOCKER_HOST_IP` at line 29:

```
export DOCKER_HOST_IP = $(shell ifconfig en0 | grep inet | grep -v inet6 | awk '{print $$2}')
```

It could be fixed using `hostname -I` as alternate.

**Comment by bokket** [comment]
May be we can install this? `sudo apt install net-tools `
Then refer to https://wiki.archlinux.org/title/Network_configuration#iproute2
and https://dubbo.apache.org/zh/blog/2019/10/01/%E7%A0%94%E7%A9%B6-dubbo-%E7%BD%91%E5%8D%A1%E5%9C%B0%E5%9D%80%E6%B3%A8%E5%86%8C%E6%97%B6%E7%9A%84%E4%B8%80%E7%82%B9%E6%80%9D%E8%80%83/
Please type `ifconfig en0` in the terminal. If you still have this problem, there is no driver.

**Comment by xavier-niu** [comment]
It works, thx.
