### ISSUE TITLE
Update the contents of the HOWTO README

### ISSUE THREAD

**Issue by bokket** [apache/dubbo-go-samples#117]
Inside the HOWTO.md guide, the
`make -f .. /.. /build/Makefile docker-up` command does not correspond to the corresponding directory, and `.. /build/makefile` operation returns a folder under `attachment`, so I think we should use the absolute path like `make -f ../ /xxx/xxx/dobbo-go samles/build/Makefile docker-up `

**Comment by AlexStocks** [comment]
@LaurenceLiZhixin pls answer this question.

**Comment by LaurenceLiZhixin** [comment]
I guess you run it on windows.
Run test on windows environment is not suggested. 
You can run the test with the following choice:
1. Run `make PROJECT_DIR=$(pwd)  BASE_DIR=$(pwd)/dist -f ../../build/Makefile docker-up` with git bash instead of `make -f ../ /xxx/xxx/dobbo-go samles/build/Makefile docker-up `
2. Run `sh start_integrate_test.sh` in the root directory of dubbo-go-samples to run all tests.

> 
> 
> Inside the HOWTO.md guide, the
> `make -f ... /... /build/Makefile docker-up` command does not correspond to the corresponding directory, and `... /build/makefile` operation returns a folder under `attachment`, so I think we should use the absolute path like `make -f ../ /xxx/xxx/dobbo-go samles/build/Makefile docker-up `

**Comment by tylitianrui** [comment]
PLS   update the [HOETO](https://github.com/apache/dubbo-go-samples/blob/master/HOWTO.md)  
contents of the HOWTO   are different from  code of demos,such as  dir   ` attachment` .
now： 
```
├── README.md
├── README_zh.md
├── go-client
│   ├── cmd
│   │   └── client.go
│   ├── conf
│   │   ├── client.yml
│   │   └── log.yml
│   └── pkg
│       └── user.go
└── go-server
    ├── cmd
    │   └── server.go
    ├── conf
    │   ├── client.yml
    │   ├── log.yml
    │   └── server.yml
    ├── docker
    │   └── docker-compose.yml
    ├── pkg
    │   └── user.go
    └── tests
        └── integration
            ├── main_test.go
            └── userprovider_test.go
```

**Comment by xavier-niu** [comment]
This issue could be closed. @LaurenceLiZhixin
