### ISSUE TITLE
There are no any integration test can be passed on MacOS 11

### ISSUE THREAD

**Issue by mark4z** [apache/dubbo-go-samples#18]
Because it found the wrong path.

excepted: .../go-server/dist...
actually:   .../go-server/tests/dist...

Running integration test for application go-server
2020/12/05 17:39:00 [InitLog] warn: ioutil.ReadFile(file:dist/darwin_amd64/release/conf/log.yml) = error:open dist/darwin_amd64/release/conf/log.yml: no such file or directory
2020/12/05 17:39:00 [consumerInit] unmarshalYmlConfig error ioutil.ReadFile(file:dist/darwin_amd64/release/conf/client.yml) = error:open dist/darwin_amd64/release/conf/client.yml: no such file or directory

I will fix it.

**Comment by zouyx** [comment]
You should run `make` follow the [README.md](https://github.com/apache/dubbo-go-samples) in dubbo-go-samples.

It points out run `make` in `helloworld/go-server` not `helloworld/go-server/tests `or run follow script in root dir
```
./integrate_test.sh helloworld/go-server
```

**Comment by mark4z** [comment]
> You should run `make` follow the [README.md](https://github.com/apache/dubbo-go-samples) in dubbo-go-samples.
> 
> It points out run `make` in `helloworld/go-server` not `helloworld/go-server/tests `or run follow script in root dir
> 
> ```
> ./integrate_test.sh helloworld/go-server
> ```

I try to run it follow and get a err

`cd helloworld/go-server`
`make -f ../../build/Makefile integration`

**Comment by zouyx** [comment]
> > You should run `make` follow the [README.md](https://github.com/apache/dubbo-go-samples) in dubbo-go-samples.
> > It points out run `make` in `helloworld/go-server` not `helloworld/go-server/tests `or run follow script in root dir
> > ```
> > ./integrate_test.sh helloworld/go-server
> > ```
> 
> I try to run it follow readMe and get a err
> 
> `cd helloworld/go-server`
> `make -f ../../build/Makefile integration`

You should run ```make -f ../../build/Makefile docker-up``` for start zookeeper and ```make -f ../../build/Makefile start``` for start provider before ```make -f ../../build/Makefile integration```.Can not  just run ```make -f ../../build/Makefile integration```

If you have not docker , you should install a zookeeper server for  integration.

**Comment by mark4z** [comment]
> > > You should run `make` follow the [README.md](https://github.com/apache/dubbo-go-samples) in dubbo-go-samples.
> > > It points out run `make` in `helloworld/go-server` not `helloworld/go-server/tests `or run follow script in root dir
> > > ```
> > > ./integrate_test.sh helloworld/go-server
> > > ```
> > 
> > 
> > I try to run it follow readMe and get a err
> > `cd helloworld/go-server`
> > `make -f ../../build/Makefile integration`
> 
> You should run `make -f ../../build/Makefile docker-up` for start zookeeper and `make -f ../../build/Makefile start` for start provider before `make -f ../../build/Makefile integration`.Can not just run `make -f ../../build/Makefile integration`
> 
> If you have not docker , you should install a zookeeper server for integration.

yep, i start zookeeper  and go-server, then integration test and got a err

**Comment by mark4z** [comment]
/dist in helloworld/go-server

and tests try to find /dist in helloworld/go-server/tests

**Comment by zouyx** [comment]
> /dist in helloworld/go-server
> 
> and tests try to find /dist in helloworld/go-server/tests

ok,you are right
