### ISSUE TITLE
delete the redundant getty config params

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go-samples#180]
![image](https://user-images.githubusercontent.com/7959374/126867729-ea2681ea-4c6a-49f4-9634-22fa9d3e30c8.png)

**Comment by AlexStocks** [comment]
cc @dongjianhui

**Comment by Mulavar** [comment]
https://github.com/apache/dubbo-go-samples/pull/199
https://github.com/apache/dubbo-go-samples/pull/200
