### ISSUE TITLE
registry/servicediscovery/nacos/go-client运行异常

### ISSUE THREAD

**Issue by wolingzong** [apache/dubbo-go-samples#191]
registry/servicediscovery/nacos/go-client/cmd/client.go<img width="1533" alt="image" src="https://user-images.githubusercontent.com/14008857/128200236-ab15d691-8345-4811-af35-4f86303eda2f.png">2021/08/04 22:21:42 [INFO] logDir:</private/var/folders/nl/jg7kstxn7r78khdhh_24x0100000gn/T/log>   cacheDir:</private/var/folders/nl/jg7kstxn7r78khdhh_24x0100000gn/T/cache>
2021-08-04T22:21:42.196+0800    WARN    config/config_loader.go:193     providerConfig is nil!
github.com/apache/dubbo-go/config.loadProviderConfig
        /Users/watson/code/golang/projects/pkg/mod/github.com/apache/dubbo-go@v1.5.7-rc1/config/config_loader.go:193
github.com/apache/dubbo-go/config.Load
        /Users/watson/code/golang/projects/pkg/mod/github.com/apache/dubbo-go@v1.5.7-rc1/config/config_loader.go:357
main.main
        /Users/watson/Documents/GitHub/dubbo-go-samples/registry/servicediscovery/nacos/go-client/cmd/client.go:60
runtime.main
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/proc.go:204
[2021-08-04/22:21:50 main.main: client.go: 63] %s

start to test dubbopanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47290ff]

goroutine 1 [running]:
main.main()
        /Users/watson/Documents/GitHub/dubbo-go-samples/registry/servicediscovery/nacos/go-client/cmd/client.go:65 +0x13f

Process finished with exit code 2

**Comment by zhaoyunxing92** [comment]
麻烦你提供下配置文件信息，可以添加到群钉钉群:23331795

**Comment by luky116** [comment]
本地试了下没有复现问题， 可以确认下你本地环境是否正常。或是加钉钉群交流下：23331795

**Comment by MasterKenway** [comment]
[fix nacos service discovery error](https://github.com/apache/dubbo-go/pull/1390) after we debug, this was casued by not define nacos group in the subscibe method, and here comes another problem that currently we only support nacos 1.4, so we suggest you  to drop you nacos version, thank you for supporting our project

**Comment by wolingzong** [comment]
nacos1.4.2 OK，nacos2.0.0 不行！
