### ISSUE TITLE
/bin/zsh下for循环错误

### ISSUE THREAD

**Issue by wolingzong** [apache/dubbo-go-samples#192]
watson@watsondeMacBook-Pro dubbo-go-samples % /bin/zsh /Users/watson/Documents/GitHub/dubbo-go-samples/start_integrate_test.sh
/Users/watson/Documents/GitHub/dubbo-go-samples/start_integrate_test.sh:88: parse error near `)'
watson@watsondeMacBook-Pro dubbo-go-samples %

**Comment by MasterKenway** [comment]
Here after we discuss about supports other shells is quite unnecessary, cause pre-installed /bin/sh on macOs and /bin/bash on linux is enough to handle this situation, so we suggest you to use just the shell we specify.
