### ISSUE TITLE
error when running the basic helloworld

### ISSUE THREAD

**Issue by lidongdong536** [apache/dubbo-go-samples#29]
i,ll running zookeeper as docker-compose and running the basic helloworld demo.i donn`t edit any config file and just do anything as docs said.The server can running success but when i seed siginal and rerun the go-server then execute error.When i wana running go-client then said "providerConfig is nil!" and go-client exit. I'll check zookeeper and found provider was success registry to zk and consumer wasn't success registry. I check "dist/linux_amd64/release/go-client.log" found some param was set null,contains:
?app.version=0.0.1&application=UserInfoClient&async=false&bean.name=UserProvider
&cluster=failover&environment=dev&generic=false
&group=
&interface=org.apache.dubbo.UserProvider
&ip=x.x.x.x
&loadbalance=
&methods.GetUser.loadbalance=
&methods.GetUser.retries=3
&methods.GetUser.sticky=false
&module=dubbo-go user-info client
&name=UserInfoClient&organization=dubbo.io
&owner=
&pid=11218&protocol=dubbo
&provided-by=
&reference.filter=cshutdown
&registry.role=0&release=dubbo-golang-1.3.0
&retries=
&side=consumer
&sticky=false&timestamp=1607913567
&version=
then i fix some param but another is still null and running exit,can everybody fix that problem?
i run at go-1.13.12
dubbo-go-samples 1.5.5 at 2020/12/14

**Comment by zouyx** [comment]
> i,ll running zookeeper as docker-compose and running the basic helloworld demo.i donn`t edit any config file and just do anything as docs said.The server can running success but when i seed siginal and rerun the go-server then execute error.When i wana running go-client then said "providerConfig is nil!" and go-client exit. I'll check zookeeper and found provider was success registry to zk and consumer wasn't success registry. I check "dist/linux_amd64/release/go-client.log" found some param was set null,contains:
> ?app.version=0.0.1&application=UserInfoClient&async=false&bean.name=UserProvider
> &cluster=failover&environment=dev&generic=false
> &group=
> &interface=org.apache.dubbo.UserProvider
> &ip=x.x.x.x
> &loadbalance=
> &methods.GetUser.loadbalance=
> &methods.GetUser.retries=3
> &methods.GetUser.sticky=false
> &module=dubbo-go user-info client
> &name=UserInfoClient&organization=dubbo.io
> &owner=
> &pid=11218&protocol=dubbo
> &provided-by=
> &reference.filter=cshutdown
> &registry.role=0&release=dubbo-golang-1.3.0
> &retries=
> &side=consumer
> &sticky=false&timestamp=1607913567
> &version=
> then i fix some param but another is still null and running exit,can everybody fix that problem?
> i run at go-1.13.12
> dubbo-go-samples 1.5.5 at 2020/12/14

* If you start ```go-client```, console print ```providerConfig is nil!``` is normal. After all, consumer doesn't need that config.
* Consumer will shut down after call Provider, you can check the code as below
https://github.com/apache/dubbo-go-samples/blob/7a992b8629964eaa1e0d6dd85cab1455b9589372/helloworld/go-client/cmd/client.go#L59

**Comment by lidongdong536** [comment]
@zouyx  3q for your answer，i‘ll check this from source code
