### ISSUE TITLE
protoc-gen-dubbo not found

### ISSUE THREAD

**Issue by tonyjt** [apache/dubbo-go-samples#312]
samples:

[rpc/grpc/](https://github.com/apache/dubbo-go-samples/blob/master/rpc/grpc/protobuf/protobuf.mk)

`go get -u dubbo.apache.org/dubbo-go/v3/protocol/grpc/protoc-gen-dubbo
`

output:
go get: module dubbo.apache.org/dubbo-go/v3@upgrade found (v3.0.0), but does not contain package dubbo.apache.org/dubbo-go/v3/protocol/grpc/protoc-gen-dubbo

**Comment by AlexStocks** [comment]
suggestion from @LaurenceLiZhixin :

```txt
3.0 没有这个接口，用这个工具：https://github.com/dubbogo/tools/tree/master/cmd/protoc-gen-dubbo3grpc

go get -u github.com/dubbogo/tools/cmd/protoc-gen-dubbo3grpc
protoc --go_out=. --dubbo3grpc_out=. ./demo.proto

3.0 不推荐用gRPC，推荐直接用triple，可与gRPC互通。
你说的这个gRPC协议是之前用于 1.5 兼容用的。
```
