### ISSUE TITLE
Error when building dubbo-go-samples/helloworld/go-server

### ISSUE THREAD

**Issue by CodeToPoem** [apache/dubbo-go-samples#36]
![image](https://user-images.githubusercontent.com/31987981/105933496-771b5c80-6089-11eb-8407-d91af63de581.png)
I run 'sudo make -f ../../build/Makefile start' and find 'PROJECT_NAME' is null, which results in the failture of go-server. 
ps: my system is macos 10.15.5

**Comment by LaurenceLiZhixin** [comment]
Thanks for your issue, there is some bug in README.md, 
Pls run ```sudo make PROJECT_NAME=go-server -f ../../../build/Makefile start``` instead.
Also, we suggest developers to config project path and run with start_integrate_test.sh script!

**Comment by xavier-niu** [comment]
Duplicated with #117
