### ISSUE TITLE
bug: seata-golang 里使用的 dubbo-getty 版本与 dubbo-go 使用的 dubbo-getty 版本不一致

### ISSUE THREAD

**Issue by lethexixin** [apache/dubbo-go-samples#50]
在使用seata模块的时候会报错，报错内容为：  

```bash
# github.com/transaction-wg/seata-golang/pkg/client/rpc_client
...\github.com\transaction-wg\seata-golang@v0.1.8\pkg\client\rpc_client\rpc_remoting_client.go:210:6: assignment mismatch: 1 variable but session.WritePkg returns 3 values
...\github.com\transaction-wg\seata-golang@v0.1.8\pkg\client\rpc_client\rpc_remoting_client.go:273:6: assignment mismatch: 1 variable but session.WritePkg returns 3 values
```

报错原因是seata-golang里使用的dubbo-getty版本较低,   
在dubbo-go@v1.5.5以上的版本中dubbo-getty使用的是v1.4.3,   
而seata-golang@v0.1.8使用的是dubbo-getty@v1.4.2 ，  
在dubbo-getty@v1.4.3 中是  WritePkg(pkg interface{}, timeout time.Duration) (totalBytesLength int, sendBytesLength int, err error)，    
而 在dubbo-getty v1.4.2 中是 WritePkg(pkg interface{}, timeout time.Duration)  err error ，   
返回的参数数量不同，所以导致了最上面的错误，请修复一下 seata-golang 的内容

**Comment by AlexStocks** [comment]
@lethexixin I think u can submit an issue to seata-golang again.
